steps:
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'rsync', '-r', '-d', '-c', './data/', 'gs://cicd-pipeline-test-bkt/test/']

## step 2 ##
- name: 'ubuntu'
  args: ['bash', './rollback.sh']

timeout: 50000s
logsBucket: 'gs://cicd-pipeline-test-bkt/test-logs/'