steps:
- name: 'gcr.io/cloud-builders/gsutil'
  entrypoint: 'bash'
  args:
  - -c
  - |
    pwd
    ls -lrt
    echo "file coping started"
    cp ./*.txt gs://cicd-pipeline-test-bkt/test/

timeout: 50000s
